site_name:        UncertainData.jl
repo_url:         https://github.com/kahaaga/UncertainData.jl
site_description: Datasets and values with associated uncertainties.
site_author:      Kristian Agas√∏ster Haaga

theme: material

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      baselevel: 2
      separator: "_"

docs_dir: 'build'

pages:
  - Package overview: index.md
  - Propagation of errors: propagation_of_errors/propagation_of_errors.md
  - Uncertain values:
    - Types of uncertain values: uncertain_values/uncertainvalues_overview.md
    - List of representations:
      - Kernel density estimates (KDE): uncertain_values/uncertainvalues_kde.md
      - Theoretical distributions with known parameters: uncertain_values/uncertainvalues_theoreticaldistributions.md
      - Theoretical distributions with fitted parameters: uncertain_values/uncertainvalues_fitted.md
      - Weighted (nested) populations: uncertain_values/uncertainvalues_populations.md
      - Values without uncertainty: uncertain_values/uncertainvalues_certainvalue.md
      - Measurements: uncertain_values/uncertainvalues_Measurements.md
    - Combining/merging: uncertain_values/merging.md
    - Extended examples: uncertain_values/uncertainvalues_examples.md

  - Uncertain datasets:
      - Types of uncertain datasets: uncertain_datasets/uncertain_datasets_overview.md
      - Uncertain index dataset: uncertain_datasets/uncertain_index_dataset.md 
      - Uncertain value dataset: uncertain_datasets/uncertain_value_dataset.md
      - Uncertain index-value dataset: uncertain_datasets/uncertain_indexvalue_dataset.md
      - Generic uncertain dataset: uncertain_datasets/uncertain_dataset.md

  - Sampling constraints:
    - Regular constraints: sampling_constraints/available_constraints.md
    - Sequential constraints:
      - List of sequential constraints: sampling_constraints/sequential_constraints.md
      - Existence of sequences: sampling_constraints/ordered_sequence_exists.md
    - Examples:
      - Constraining uncertain values: sampling_constraints/constrain_uncertain_values.md
  - Binning:
    - Scalar valued data: binning/bin_scalardata.md
    - Uncertain data: binning/bin_BinnedResampling.md
  - Resampling:
    - Overview: resampling/resampling_overview.md
    - Uncertain values: 
      - Resampling uncertain values: resampling/resampling_uncertain_values.md
    - Uncertain value collections: 
      - Resampling uncertain collections: resampling/resampling_uncertain_datasets.md
      - List of resampling schemes: resampling/resampling_schemes/resampling_schemes_uncertain_value_collections.md
      - resample: resampling/resampling_schemes/resampling_with_schemes_uncertain_value_collections.md
    - Uncertain index-value collections: 
      - Resampling index-value collections: resampling/resampling_uncertain_indexvalue_datasets.md
      - List of resampling schemes: resampling/resampling_schemes/resampling_schemes_uncertain_indexvalue_collections.md
      - resample: resampling/resampling_schemes/resampling_with_schemes_uncertain_indexvalue_collections.md
      - Sequential resampling: 
        - Overview: resampling/sequential/resampling_uncertaindatasets_sequential.md
        - Strictly increasing: resampling/sequential/strictly_increasing.md
        - Strictly decreasing: resampling/sequential/strictly_decreasing.md
        - Index-value datasets: resampling/sequential/resampling_indexvalue_sequential.md
      - Interpolation:
        - Overview: resampling/interpolation/interpolation.md
        - Gridded interpolation: resampling/interpolation/gridded.md
    - Resampling in-place: resampling/resampling_inplace.md
  - Mathematics: 
      - Elementary operations: mathematics/elementary_operations.md
      - Trigonometric functions: mathematics/trig_functions.md

  - Statistics:
    - Basics: 
      - Overview: uncertain_statistics/core_stats/core_statistics.md
      - Point estimates on values: uncertain_statistics/core_stats/core_statistics_point_estimates.md
      - Pairwise estimates on values: uncertain_statistics/core_stats/core_statistics_pairwise_estimates.md
      - Estimates on single uncertain value collections: uncertain_statistics/core_stats/core_statistics_datasets_single_dataset_estimates.md
      - Estimates on pairs of uncertain value collections: uncertain_statistics/core_stats/core_statistics_datasets_pairwise_estimates.md
      #- Single uncertain dataset estimates: uncertain_statistics/core_stats/core_statistics_datasets.md
    - Hypothesis tests:
      - Overview: uncertain_statistics/hypothesistests/hypothesis_tests_overview.md
      - One sample t-test: uncertain_statistics/hypothesistests/one_sample_t_test.md
      - Equal variance t-test: uncertain_statistics/hypothesistests/equal_variance_t_test.md
      - Unequal variance t-test: uncertain_statistics/hypothesistests/unequal_variance_t_test.md
      - Exact Kolmogorov-Smirnov test: uncertain_statistics/hypothesistests/exact_kolmogorov_smirnov_test.md
      - Approximate two-sample Kolmogorov-Smirnov test: uncertain_statistics/hypothesistests/approximate_twosample_kolmogorov_smirnov_test.md
      - Jarque-Bera test: uncertain_statistics/hypothesistests/jarque_bera_test.md
      - Mann-Whitney u-test: uncertain_statistics/hypothesistests/mann_whitney_u_test.md
      - Anderson-Darling test: uncertain_statistics/hypothesistests/anderson_darling_test.md
  
  - Tutorials: 
    - List of tutorials: tutorials/tutorial_overview.md
    - Regularising data:
      - Binned resampling: tutorials/tutorial_transforming_data_to_regular_grid.md
  - Implementing algorithms for uncertain data: implementing_algorithms_for_uncertaindata.md
  
  - Changelog: changelog.md
  
  - Publications and software: publications.md
    
  - Citing: citing.md