name: TagBot
on:
  issue_comment:  # THIS BIT IS NEW
    types:
      - created
  schedule:
    - cron: 0 * * * *
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'

    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
